language: go

sudo: false

services:
  - docker

go:
  - "1.11.5"

before_install:
  - go get golang.org/x/lint/golint
  - go get github.com/operator-framework/operator-sdk/cmd/operator-sdk

env:
  - TARGET=test-verbose
  - TARGET=lint
  - TARGET=docker

script: make $TARGET
