[[override]]
  name = "k8s.io/api"
  # revision for tag "kubernetes-1.14.1"
  revision = "6e4e0e4f393bf5e8bbff570acd13217aa5a770cd"
[[override]]
  name = "k8s.io/apiextensions-apiserver"
  # revision for tag "kubernetes-1.14.1"
  revision = "727a075fdec8319bf095330e344b3ccc668abc73"
[[override]]
  name = "k8s.io/apimachinery"
  # revision for tag "kubernetes-1.14.1"
  revision = "6a84e37a896db9780c75367af8d2ed2bb944022e"
[[override]]
  name = "k8s.io/client-go"
  # revision for tag "kubernetes-1.14.1"
  revision = "1a26190bd76a9017e289958b9fba936430aa3704"
[[override]]
  name = "github.com/coreos/prometheus-operator"
  version = "=v0.31.1"
[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.2.2"
[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  version = "=v0.11.0"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"